
version: 2.1
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/node:16.13.1-browsers
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package-lock.json" }}
          - v1-dependencies-
      - run:
          name: Install dependencies
          command: npm install
      - save_cache:
          key: v1-dependencies-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
      - run:
          name: Build
          command: |
            if [ $CIRCLE_BRANCH = 'development' ]; then
              npm run build
            fi
      - persist_to_workspace:
          root: .
          paths:
            - .
  deploy:
    working_directory: ~/repo
    docker:
      - image: innovatorjapan/awscli:latest
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Deploy
          command: |
            if [ $CIRCLE_BRANCH = 'master' ]; then
              aws s3 sync dist/angular-material-starter/ s3://angular-material-starter-bucket/ --delete --exact-timestamps;
            fi
  deployQA:
   working_directory: ~/repo
    docker:
      - image: circleci/node:16.13.1-browsers
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package-lock.json" }}
          - v1-dependencies-
      - run:
          name: Install dependencies
          command: npm install
      - save_cache:
          key: v1-dependencies-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
      - run:
          name: Build
          command: |
            if [ $CIRCLE_BRANCH = 'development' ]; then
              npm run build:qa
            fi
workflows:
  version: 2.1
  build_and_deploy:
    jobs:
      - build:
          filters:
            branches:
              only:
                - development
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - development
      - deployQA:
          filters:
            branches:
              only:
                - development
