version: 0.2
env:
  variables:
    S3_BUCKET: "3clogic-synergy1"
    BUILD_FOLDER: "dist"
phases:
  install:
    runtime-versions:
      nodejs: 16
  pre_build:
    commands:
      - echo Installing source NPM dependencies.....
      - npm install
      - echo "pre_build stage completed"
  build:
    commands:
      - echo Build started on `date`
      - npm run build
artifacts:
  files:
      - '**/*'
  base-directory: 'dist/synergy*'
