name: Sync Bucket
version: 0.2
on:
  push:
    branches: development
env:
  variables:
    S3_BUCKET: "3clogic-synergy"
    BUILD_FOLDER: "dist"
jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
    pre_build:
    commands:
      - echo Installing source NPM dependencies.....
      - npm install
      - echo "pre_build stage completed"
  build:
    commands:
      - echo Build started on `date`
      - npm run build
artifacts:
  files:
      - '**/*'
  base-directory: 'dist/synergy*'
